src/blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import PostFeed

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.post_list_view, name='post_list_view'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-\w]+)$',
        views.post_detail_view, name= 'post_detail_view'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-\w]+)/edit/$',
        views.post_update, name='post_edit'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-\w]+)/delete/$',
        views.post_delete, name='post_delete'),

    url(r'^feed/$', PostFeed(), name='post_feed'),

]

src/tejgaon_college/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts' : PostSitemap
}

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'git ),
    url(r'^admin/', admin.site.urls),
    url(r'^departments/', include('department.urls', namespace= 'department')),
    url(r'^teachers/', include('teacher.urls', namespace='teacher')),
    url(r'^gallery/', include('photologue.urls', namespace='photologue')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^sitemap\.xml$',sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('default_page.urls', namespace='default_page')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Custom Manager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


# Our Post Model

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    content = models.TextField()
    upload_image = models.ImageField(blank=True, null=True,height_field='height_field', width_field='width_field', upload_to='blog')
    height_field = models.IntegerField(blank=True, null=True)
    width_field = models.IntegerField(blank=True, null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    # The default manager
    objects = models.Manager()

    # # Custom made manager
    Published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail_view', args=[self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug])

    def edit(self):
        return reverse('blog:post_edit', args=[self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug])

    def destroy(self):
        return reverse('blog:post_delete', args=[self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug])

src/blog/forms.py
from .models import Post
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'upload_image'
        ]

src/blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from .models import Post
from .forms import PostForm


def post_list_view(request):
    list_objects = Post.Published.all()
    paginator = Paginator(list_objects, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts})


def post_detail_view(request, year, month, day, slug):
    post = get_object_or_404(Post, slug=slug, publish__year=year, publish__month=month, publish__day=day)
    context ={
        'post': post
    }
    return render(request, 'blog/post/detail.html',context)


def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
    context = {
        "form": form,
    }
    return render(request, 'blog/post/add.html', context)


def post_update(request, year, month, day, slug):
    instance = get_object_or_404(Post, slug=slug, publish__year=year, publish__month=month, publish__day=day)
    form = PostForm(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
    context ={
        'instance': instance,
        'form': form
    }
    messages.success(request, 'Successfully updated')
    return render(request, 'blog/post/update.html',context)


def post_delete(request, year, month, day, slug):
    post = get_object_or_404(Post, slug=slug, publish__year=year, publish__month=month, publish__day=day)
    if post.author == request.user:
        post.delete()
        messages.success(request, 'Successfully deleted')
        return redirect('blog:post_list_view')

src/templates/blog/post/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    create-post
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-md-8 mt-2">
            <h1  style="font-family: 'Lobster';">Create New Post!</h1>
            <hr>
            <form method="POST" action="">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block mb-3">Create Post</button>
            </form>
        </div>
    </div>

    {#    <div class="row">#}
    {#        <div class="col-md-8">#}
    {#            <h1 class="text-center pt-4 "> Create Blog post</h1>#}
    {#            <hr>#}
    {#            <form action="" method="POST">{% csrf_token %}#}
    {#                                {{ form.title }}#}
    {#                <br>#}
    {#                {{ form.body }}#}
    {#                    <div class="form-group row">#}
    {#                        <label for="title" class="col-sm-2 col-form-label">Title:</label>#}
    {#                        <div class="col-sm-10">#}
    {#                            <input type="text" class="form-control" id="title" placeholder="Title goes here..........">#}
    {#                        </div>#}
    {#                    </div>#}
    {#                    <div class="form-group row">#}
    {#                        <label for="body" class="col-sm-2 col-form-label">Content:</label>#}
    {#                        <div class="col-sm-10">#}
    {#                            <textarea name="body" id="body" cols="65" rows="10" placeholder="Content goes here........"></textarea>#}
    {#                        </div>#}
    {#                    </div>#}
    {##}
    {##}
    {#                    <div class="form-group row">#}
    {#                        <div class="col-sm-10 offset-2">#}
    {#                            <button type="submit" class="btn btn-primary btn-block">Create Post</button>#}
    {#                        </div>#}
    {#                    </div>#}
    {#                </form>#}
    {#        </div>#}
    {#    </div>#}

    {#    <div class="row">#}
    {#    <div class="col-md-12">#}
    {#        <form method="POST"> {%csrf_token%}#}
    {##}
    {#            {% for error in form.non_field_errors %}#}
    {#                <div class="form-group has-errors text-danger small">#}
    {#                    {{error}}#}
    {#                </div>#}
    {#            {% endfor %}#}
    {#            {% for field in form %}#}
    {#                <div class="form-group has-errors text-danger small">#}
    {#                    {{field.errors}}#}
    {#                </div>#}
    {#                <div class="form-group has-errors text-danger small">#}
    {#                </div>#}
    {#                <div class="form-group">#}
    {##}
    {#                    {{ field }}#}
    {#                </div>#}
    {#            {% endfor %}#}
    {#            <button type="submit" class="btn btn-primary btn-block mb-4">Create post</button>#}
    {#        </form>#}
    {#    </div>#}
    {#    </div>#}
{% endblock content %}

src/templates/blog/post/detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="row pt-2 text-justify">

        <div class="col-md-9">
            <h2 style="font-family: 'Lobster'; color:#164A4A;">{{ post.title }}</h2>
              {% if post.author == request.user %}
                    <a style="color: green;" href="{{ post.edit }}"><span class="fa fa-edit fa-2x"></span></a>
                <a style="color: red;" href="{{ post.delete }}"><span class="fa fa-trash-o fa-2x"></span></a>
                {% endif %}
            <p class="small  text-muted" style="color: #777777; ">Published {{ post.publish|timesince }} ago {{ post.published }} by {{ post.author }}</p>
            {% if post.upload_image %}
                <img style="height: 300px;" class="card-img img-responsive" src="{{ post.upload_image.url }}" alt="Blog Image">
            {% endif %}
            <div class="fb-like mt-2"
                 data-href="{{request.build_absolute_uri}}" data-layout="standard"
                 data-action="like" data-size="small" data-show-faces="true" data-share="true">
            </div>
            <p style="font-family: 'Lora', serif; font-weight: bold;">{{ post.content|linebreaks }}</p>

            <div class="fb-comments" data-href="{{request.build_absolute_uri}}"
                 data-numposts="2">
            </div>
        </div>

        <div class="col-md-3  jumbotron">
            <h3  style="font-family: Lobster;">Tejgaon College Blog</h3>
            <hr>
            <p><a href="{% url "blog:post_feed" %}" target="_blank"> <span style="color: red;" class="fa fa-rss fa-2x"></span> Subscribe to RSS Feed</a></p>
        </div>
    </div>




{% endblock %}

src/templates/blog/post/list.html
{% extends "base.html" %}

{% block title %}Our Blog{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div class="row mt-4">
                <div class="col-md-6">
                    <h2 style="color: #164A4A;">Recent Posts</h2>

                </div>
                <div class="col-md-6">
                    <a href="{% if request.user.is_authenticated %}
                    {% url 'blog:post_create' %}
                    {% else %}
                    {% url 'login' %}
                    {% endif %}"><button class="btn btn-outline-info btn-block">Create Post</button></a>

                </div>
            </div>
            <hr>
            {% for post in posts %}
                <h2 style="font-family: 'Lobster';">{{ post.title }}</h2>
                {% if post.author == request.user %}
                    <a style="color: green;" href="{{ post.edit }}"><span class="fa fa-edit "></span></a>
                <a style="color: red;" href="{{ post.destroy }}"><span class="fa fa-trash-o "></span></a>

                {% endif %}

                {% if post.author.get_full_name %}
                    <p class="small" style="color: #777777; font-family: 'Lora', serif;">Published {{ post.publish|timesince }} ago by {{ post.author.get_full_name }}</p>
                {% elif post.author%}
                    <p class="small" style="color: #777777; font-family: 'Lora', serif;">Published {{ post.publish|timesince }} ago by {{ post.author }}</p>

                {% endif %}
                {% if post.upload_image %}
                    <img style="height: 400px;" class="card-img img-responsive" src="{{ post.upload_image.url }}" alt="Blog Image">


                {% endif %}
                <div class="fb-like mt-2" data-href="{{request.build_absolute_uri}}"
                     data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true">
                </div>
                <p style="font-weight: initial; font-family: 'Lora', serif;" class="pt-2">{{ post.content|truncatewords:31}}<a href="{{ post.get_absolute_url }}">View more</a></p>


            {% endfor %}
            {% include "blog/pagination.html" with page=posts %}

        </div>
        <div class="col-md-4 jumbotron  pt-0">
            <h2 style="font-family: 'Lobster';" class="page-header">Tejgaon College Blog</h2>
            <hr>
            <p><a href="{% url "blog:post_feed" %}" target="_blank"> <span style="color: red;" class="fa fa-rss fa-2x"></span> Subscribe to RSS Feed</a></p>
        </div>

    </div>
{% endblock %}

src/templates/blog/post/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    update-post
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-md-8 mt-2">
            <h1  style="font-family: 'Lobster';">Update Post!</h1>
            <hr>
            <form method="POST" action="">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block mb-3">Update Post</button>
            </form>
        </div>
    </div>

{% endblock %}