src/blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import PostFeed

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.post_list_view, name='post_list_view'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-\w]+)$',
        views.post_detail_view, name= 'post_detail_view'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-\w]+)/edit/$',
        views.post_update, name='post_edit'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-\w]+)/delete/$',
        views.post_delete, name='post_delete'),

    url(r'^feed/$', PostFeed(), name='post_feed'),

]

src/teacher/urls.py
from django.conf.urls import url
from . import views

app_name='teacher'

urlpatterns = [
    url(r'^$',views.index, name='index' ),
    url(r'^(?P<slug>[-\w]+)/$',views.view, name = 'view'),



]

src/tejgaon_college/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts' : PostSitemap
}

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'git ),
    url(r'^admin/', admin.site.urls),
    url(r'^departments/', include('department.urls', namespace= 'department')),
    url(r'^teachers/', include('teacher.urls', namespace='teacher')),
    url(r'^gallery/', include('photologue.urls', namespace='photologue')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^sitemap\.xml$',sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('default_page.urls', namespace='default_page')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/teacher/models.py
from django.db import models
from department.models import Department
from django.template.defaultfilters import slugify
from django.core.validators import URLValidator



# Create your models here.
class Teacher(models.Model):
    designation_type = (
        ('Lecturer', 'Lecturer'),
        ('Professor', 'Professor'),
        ('A. Professor', 'Assistant Professor'),
    )
    # status_type = (
    #     ('Professional', 'Professional'),
    #     ('General', 'General')
    # )
    dept_head =(
        ('yes','yes'),
        ('no','no')
    )

    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    phone_number = models.CharField(max_length=20)
    facebook_profile = models.URLField(blank=True, null=True, validators=[URLValidator()])

    designation = models.CharField(max_length=50, choices=designation_type,)
    department_head = models.CharField(choices=dept_head, max_length= 10)
    department = models.ForeignKey(Department,on_delete=models.CASCADE, related_name='departments')
    studied_at = models.CharField(max_length=200)
    slug = models.SlugField(editable=False)
    about_teacher = models.TextField(max_length=5000)
    upload_image = models.ImageField(height_field='height_field', width_field='width_field',upload_to='img')
    height_field = models.IntegerField(default=750)
    width_field = models.IntegerField(default=1000)
    date_of_birth = models.DateField(auto_now=False, auto_now_add=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.slug

    def save(self):
        self.slug = '%s' % (
            slugify(self.name)
        )
        super(Teacher, self).save()

src/teacher/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from .models import Teacher

# Create your views here.


def index(request):
    teachers = Teacher.objects.all().order_by('-updated_at')
    paginator = Paginator(teachers, 4) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        teachers = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        teachers = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        teachers = paginator.page(paginator.num_pages)

    context = {
            'teachers': teachers
    }
    return render(request,'teacher/index.html', context)


def view(request, slug):
    teacher = Teacher.objects.get(slug=slug)
    context = {
        'teacher': teacher,

    }
    return render(request, 'teacher/view.html', context)

src/templates/teacher/index.html
{% extends 'base.html' %}

{% block title %}
    View-all-teacher-list
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-10">
            <h1 class="text-center" style="font-family: 'Lobster'; color:#164A4A;">All Teachers of Tejgaon College</h1>
            <hr>
            {% if teachers %}

                <div class="row mt-2">
                    {% for teacher in teachers%}

                        <div class="col-md-3">
                            <div class="card  p-1 mb-2">
                                <img class="card-img-top img-fluid" src="{{teacher.upload_image.url}}" alt="Card image cap">
                                <div class="card-block">
                                    <h4 class="card-title  text-center mt-1"><strong>{{teacher.name}}</strong> </h4>
                                    <h6 class=" pt-0 card-subtitle text-center">{{teacher.designation}} of {{teacher.department.name}} Department</h6>
                                    <p class="card-text text-center">{{teacher.about_teacher|truncatechars:60}}<a href="{% url "teacher:view" slug=teacher.slug %}">view more</a></p>
                                </div>
                            </div>
                        </div>
                    {% endfor%}

                </div>
            {% else %}
                <h1 class="text-danger text-center ">There is no teacher add yet!</h1>
            {% endif %}


            <div class="row">
                <div class="col-md-12 d-flex justify-content-center ">
                    <div class="pagination ">
        <span class="step-links">
          {% if teachers.has_previous %}
              <a href="?page={{ teachers.previous_page_number }}">
            <i class="fa fa-angle-double-left fa-lg" aria-hidden="true"></i>
              Previous
          </a>
          {% endif %}

            <span class="current">
            Page {{ teachers.number }} of {{ teachers.paginator.num_pages }}.
          </span>

            {% if teachers.has_next %}
                <a href="?page={{ teachers.next_page_number }}">Next
           <i class="fa fa-angle-double-right fa-lg" aria-hidden="true"></i>

         </a>
            {% endif %}
       </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div style="" class="card mt-5">
                <div class="card-text font-weight-bold text-center">
                    Quick link
                </div>
                {% include '_partial/sidebar.html' %}

            </div>
        </div>
    </div>
{% endblock %}

src/templates/teacher/view.html
{% extends "base.html" %}
{% block title %}
    {{teacher.name}}
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-10">
            <div class="card mb-1">
                <img style="height: 400px;" class="card-img-top" src="{{ teacher.upload_image.url}}" alt="Card image cap">
                <div class="card-body">
                    <h4 class="card-title text-uppercase text-center"><strong>{{teacher.name}}</strong></h4>
                    <h4 class=" card-title text-center text-capitalize"> teacher of {{teacher.department.name}} department at tejgaon college</h4>
                    <nav>
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</a>
                            <a class="nav-item nav-link " id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">At a glance
                            </a>
                        </div>
                    </nav>
                    <div class="tab-content" id="nav-tabContent">

                        <div class="tab-pane fade active show" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                            <p class="card-text pt-2">{{ teacher.about_teacher }}</p>
                            <p class="text-muted"><small>Updated: {{ teacher.updated_at|timesince }}</small></p>

                        </div>
                        <div class="tab-pane fade " id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                            <div class="list-group m-3 p-3">
                                <button type="button" class="list-group-item  "><i class="fa fa-user-circle fa-x"></i> Name: {{ teacher.name }}</button>
                                {% if teacher.department_head == 'yes' %}
                                    <button type="button" class="list-group-item "><i class="fa fa-user fa-x" aria-hidden="true"></i> Head of {{ teacher.department.name }} Department</button>

                                {% endif %}
                                <button type="button" class="list-group-item "><i class="fa fa-cog" aria-hidden="true"></i> Designation: {{ teacher.designation }}</button>
                                <button type="button" class="list-group-item "><i class="fa fa-graduation-cap" aria-hidden="true"></i> Studied: {{ teacher.studied_at }}</button>
                                <button type="button" class="list-group-item  " ><i class="fa fa-birthday-cake" aria-hidden="true"></i> Date of Birth: {{ teacher.date_of_birth }}</button>
                                 {% if teacher.facebook_profile %}
                                    <button type="button" class="list-group-item "><i class="fa fa-facebook" aria-hidden="true"></i><a  href="{{ teacher.facebook_profile }}"> Facebook </a></button>

                                {% endif %}
                                                        <p class="text-muted pt-1"><small>Updated: {{ teacher.updated_at|timesince }}</small></p>

                            </div>

                        </div>
                    </div>
                    {#                    <p style="font-family: 'font-family: 'PT Serif', serif;'" class="card-text text-justify">{{teacher.about_teacher}}</p>#}
                    {#                    <p class="card-text"><small class="text-muted">Updated: {{teacher.updated_at|timesince}} ago</small></p>#}
                </div>
            </div>

        </div>
        <div class="col-md-2">


            <div class="card mt-5">
                <div class="card-text font-weight-bold text-center">
                    Quick link
                </div>
                 {% include '_partial/sidebar.html' %}

            </div>

        </div>
    </div>
{% endblock content %}