src/blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import PostFeed

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.post_list_view, name='post_list_view'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-\w]+)$',
        views.post_detail_view, name= 'post_detail_view'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-\w]+)/edit/$',
        views.post_update, name='post_edit'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/(?P<slug>[-\w]+)/delete/$',
        views.post_delete, name='post_delete'),

    url(r'^feed/$', PostFeed(), name='post_feed'),

]

src/default_page/urls.py
from django.conf.urls import url
from . import views

app_name='default_page'

urlpatterns = [
    url(r'^$', views.home, name='home_page' ),
    url(r'^about-us/$', views.about, name='about_us' ),
    url(r'^about-us/(?P<slug>[-\w]+)$', views.about_us_view, name='about_us_single_view.html' ),
    url(r'^(?P<slug>[-\w]+)/$', views.view, name='view'),


]	

src/teacher/urls.py
from django.conf.urls import url
from . import views

app_name='teacher'

urlpatterns = [
    url(r'^$',views.index, name='index' ),
    url(r'^(?P<slug>[-\w]+)/$',views.view, name = 'view'),



]

src/tejgaon_college/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts' : PostSitemap
}

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'git ),
    url(r'^admin/', admin.site.urls),
    url(r'^departments/', include('department.urls', namespace= 'department')),
    url(r'^teachers/', include('teacher.urls', namespace='teacher')),
    url(r'^gallery/', include('photologue.urls', namespace='photologue')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^sitemap\.xml$',sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('default_page.urls', namespace='default_page')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/_partial/about_college.html
<div class="card  mt-1">
		<div class="row">
			<div class="col-md-8">
				<p class="mt-2 h4 text-center card-title"><b>WELCOME TO TEJGAON COLLEGE</b></p>
				<hr>
				<div class="row p-1">
					<div class=" col-md-6">
						<div>
							<iframe height="320px;" class="embed-responsive" src="https://www.youtube.com/embed/IFZfjHnHFXY" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
						</div>
					</div>
					<div class="col-md-6">
						<p class="text-justify  card-text">
							<span style=" font-family: 'font-family: 'PT Serif', serif;'">{{about_college.description|truncatechars:650}}</span>

							<a href="{% url "default_page:view" slug=about_college.slug %} ">Learn More</a>
{#							<a href="{% url 'default_page:view' slug=about_college.slug %}">Learn More</a>#}


						</p>
					</div>
				</div>
			</div>
			<div class="col-md-4 pl-5">
				<div class="related_post_sec">
					<p class="mt-2 h4 text-center card-title"><b>LATEST NEWS </b></p>
                    <p style="color: green;" class="text-center"><b>Today:</b>{% now "jS F Y g:i:sA" %}</p>
					<hr>
					<div id="news-container">
						<ul>
							<li>

								<a href="single-post-right-sidebar.html"><h4>Offered in small class sizes with great emphasis...</h4></a>
								<span class="date">Posted: <a href="single-post-right-sidebar.html">January 24, 2015</a></span>
							</li>
							<li>

								<a href="single-post-right-sidebar.html"><h4>Offered in small class sizes with great emphasis...</h4></a>
								<span class="date">Posted: <a href="single-post-right-sidebar.html">January 24, 2015</a></span>
							</li>
							<li>

								<a href="single-post-right-sidebar.html"><h4>Offered in small class sizes with great emphasis...</h4></a>
								<span class="date">Posted: <a href="single-post-right-sidebar.html">January 24, 2015</a></span>
							</li>
							<li>

								<a href="single-post-right-sidebar.html"><h4>Offered in small class sizes with great emphasis...</h4></a>
								<span class="date">Posted: <a href="single-post-right-sidebar.html">January 24, 2015</a></span>
							</li>
							<li>

								<a href="single-post-right-sidebar.html"><h4>Offered in small class sizes with great emphasis...</h4></a>
								<span class="date">Posted: <a href="single-post-right-sidebar.html">January 24, 2015</a></span>
							</li>
						</ul>

					</div>
					<button class="btn btn-outline-info btn-block mt-3 mb-2">View More News</button>
				</div>

			</div>
		</div>

	</div>

src/templates/_partial/banner.html
{% load static %}
<div class="row">
    <div class="col-md-12">
        <a href="{% url "default_page:home_page" %}">
            <img style="width: 100%; height: 150px;" src="{% static 'img/tc_banner.jpg' %}" alt="">
        </a>
    </div>
</div>

src/templates/_partial/fb_sdk.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.11&appId=301618213652311';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

src/templates/_partial/footer.html
<footer>
    <div class="menuFooter ">
        <div class="container">
            <div class="row ">

                <div class="col-sm-3 col-xs-6">
                    <ul class="menuLink">
                        <li class="text-uppercase text-center font-weight-bold"> Visitor counter</li>
                        <li class="pt-2">


                        <!-- BEGIN: Powered by Supercounters.com -->
                        <center><script type="text/javascript" src="//widget.supercounters.com/ssl/flag.js"></script>
                            <script type="text/javascript">sc_flag(1468436,"f7f7f7","000000","0f0a0f",2,10,0,0)</script>
                            <br><noscript><a href="http://www.supercounters.com/">Flag Counter</a></noscript>
                        </center>
                        <!-- END: Powered by Supercounters.com -->
                        </li>

                    </ul>
                </div><!-- col-sm-3 col-xs-6 -->

                <div class="col-sm-3 col-xs-6 borderLeft">
                    <ul class="menuLink">
                        <li><a href="{% url 'department:index' %}">All Departments</a></li>
                        <li><a href="buying-steps.html">Admission</a></li>
                        <li><a href="photo-gallery3col.html">Photo Gallery</a></li>
                        <li><a href="international_students.html">International Students</a></li>
                    </ul>
                </div><!-- col-sm-3 col-xs-6 -->

                <div class="col-sm-3 col-xs-6 borderLeft">
                    <div class="footer-address">
                        <h5>Location:</h5>
                        <address>
                            Tejgaon College<br>
                            1211,Indira Road<br>
                            Dhaka
                        </address>
                        <a href="contact-us.html"><span class="place"><i class="fa fa-map-marker"></i>Main Campus</span></a>
                    </div>
                </div><!-- col-sm-3 col-xs-6 -->

                <div class="col-sm-3 col-xs-6 borderLeft">
                    <div class="socialArea">
                        <h5>Find us on:</h5>
                        <ul class="list-inline ">
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="https://www.facebook.com/groups/CSEdept.TejgaonCollegeDhaka/" target= "blank"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
                            <li><a href="#"><i class="fa fa-flickr"></i></a></li>
                            <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                        </ul>
                    </div><!-- social -->
                    <div class="contactNo">
                        <h5>Call us on:</h5>
                        <h3>012-3434-456768</h3>
                    </div><!-- contactNo -->
                </div><!-- col-sm-3 col-xs-6 -->

            </div><!-- row -->
        </div><!-- container -->
    </div><!-- menuFooter -->

    <div class="footer ">
        <div class="container">
            <div class="row ">
                <div class="col-sm-6 col-xs-12 copyRight">
                    <p>© 2016 Copyright Tejgaon College Project developed by <a href="http://www.gitlab.com/yaimran21">Md Imran Hossain</a></p>
                </div><!-- col-sm-6 col-xs-12 -->
                <div class="col-sm-6 col-xs-12 privacy_policy">
                    <a href="contact-us.html">Contact us</a>

                    <a href="privacy-policy.html">Privacy Policy</a>
                </div><!-- col-sm-6 col-xs-12 -->
            </div><!-- row clearfix -->
        </div><!-- container -->
    </div><!-- footer -->
</footer>

src/templates/_partial/head.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<!-- PLUGINS CSS STYLE -->
<!-- Google fonts -->
<link href="https://fonts.googleapis.com/css?family=Cardo|Gentium+Book+Basic" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Merriweather+Sans|Roboto+Slab" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">



<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">



{% load static %}
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">

<link rel="icon" type="image/png"  href="{% static 'img/favicon.png' %}">
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
<link href="{% static 'css/custom/custom_style.css' %}" rel="stylesheet">
<link href="{% static 'css/custom/default.css' %}" rel="stylesheet">
<link href="{% static 'css/custom/gallery.css' %}" rel="stylesheet">
{#<link href="{% static 'css/custom/style.css' %}" rel="stylesheet">#}

{#Gallery css#}
<link href="{% static 'css/gallery/screen.css' %}" rel="stylesheet">
{#Gallery css#}

src/templates/_partial/js.html
{% load static %}
<!-- JQUERY SCRIPTS -->

<script src="{% static 'js/jquery-3.2.1.slim.min.js'%}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- News Start -->
<script src="{% static 'js/jquery.js'%}"></script>
<script src="{% static 'js/jquery.vticker-min.js' %}"></script>
<!-- News End -->
{#Gallery #}
<script src="{% static 'js/html5shiv.min.js' %}"></script>
<script src="{% static 'js/respond.min.js' %}"></script>
<script src="{% static 'js/project.js' %}"></script>


{#Gallery #}

src/templates/_partial/main_nav.html
{% load static%}
<nav class="navbar navbar-expand-lg navbar-light  sticky-top " style="background-color: #e3f2fd;">
    <a class="navbar-brand {% if '/' in request.path %}active{% endif %}" href="{% url "default_page:home_page" %}"><img style="height: 40px;" src="{% static 'img/logo.jpg' %}" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if '' not in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url "default_page:home_page" %}"><span class="fa fa-home"></span>Home</a>
            </li>
            <li class="nav-item {% if 'about-us'  in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url 'default_page:about_us' %}"><span class="fa fa-info-circle"></span>About us</a>
            </li>
            <li class="nav-item {% if 'departments' in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url "department:index" %}">
                    <span class="fa fa-university"></span>Department</a>
            </li>
            <li class="nav-item {% if 'teachers' in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url 'teacher:index' %}"><span class="fa fa-user"></span>Teacher</a>
            </li>
            <li class=" nav-item   {% if 'blog' in request.path %}active{% endif %}">
                <a class="nav-link " href="{% url 'blog:post_list_view' %}" >
                   <span class="fa fa-comments-o"></span>Blog
                </a>
            </li>
            <li class="nav-item dropdown {% if 'gallery' in request.path %}active{% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"  aria-expanded="false">
                   <span class="fa fa-picture-o"></span>Gallery
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'photologue:gallery-list' %}">Gallery list views</a>
                    <a class="dropdown-item" href="{% url 'photologue:pl-gallery-archive' %}">Gallery date views</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'photologue:photo-list' %}">Photo list views</a>
                    <a class="dropdown-item" href="{% url 'photologue:pl-photo-archive' %}">Photo date views</a>
                </div>
            </li>

        </ul>
   {% if user.is_authenticated %}

       <ul>
       <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"  aria-expanded="false">
                   <span class="fa fa-user-circle"></span>       {{ request.user.get_full_name }}

                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'photologue:gallery-list' %}"><i class="fa fa-user" aria-hidden="true"></i>
 Profile</a>
                    <a class="dropdown-item" href="{% url 'photologue:pl-gallery-archive' %}"><i class="fa fa-cogs" aria-hidden="true"></i>
 Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>
 Sign Out</a>
                </div>
            </li>
       </ul>
    {% endif %}

{#        <form class="form-inline ">#}
{#            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#            <button class="btn btn-outline-success" type="submit">Search</button>#}
{#        </form>#}
    </div>
</nav>

src/templates/_partial/popular_department.html
  {% load static %}
  <div class="popular_dept">
    <div class="row mt-1">
      <div class="col-md-12">
       <p style="color: white; margin-top: 10px;" class="text-center h3"><b>OUR POPULAR DEPARTMENTS</b></p>
     </div> 
   </div>
   <div class="row">
    {% for department in departments%}
    <div class="col-md-3">
                <div class="card  p-1 mb-2">
                    <img class="card-img-top img-fluid" src="{{department.upload_image.url}}" alt="Card image cap">
                    <div class="card-block">
                      <h4 class="card-title text-center">{{department.name}} Department</h4>
                      <p class="card-text text-center">{{department.details|truncatechars:50}}<a href="{% url "department:view" slug=department.slug pk=department.pk %}">view more</a></p>
                  </div>
              </div>
    </div>
    {% endfor%}

    

</div>
</div>

src/templates/_partial/sidebar.html
<ul class="list-group list-group-flush text-capitalize ">
    <li class="list-group-item  p-1"><a href="{% url "department:index" %}">Departments list
        <i class="fa fa-angle-double-right fa-lg" aria-hidden="true"></i>
    </a></li>

    <li class="list-group-item  p-1"><a href="{% url "teacher:index" %}">Teachers list
        <i class="fa fa-angle-double-right fa-lg" aria-hidden="true"></i>

    </a></li>

    <li class="list-group-item  p-1">
        <a  href="{% url 'photologue:gallery-list' %}">Gallery list views
            <i class="fa fa-angle-double-right fa-lg" aria-hidden="true"></i></a>

    </li>
    <li class="list-group-item  p-1">
        <a  href="{% url 'photologue:pl-gallery-archive' %}">Gallery date views
            <i class="fa fa-angle-double-right fa-lg" aria-hidden="true"></i>
        </a>


    </li>
    <li class="list-group-item  p-1">
        <a href="{% url 'photologue:photo-list' %}">Photo list views
            <i class="fa fa-angle-double-right fa-lg" aria-hidden="true"></i>
        </a>


    </li>
    <li class="list-group-item  p-1">
        <a  href="{% url 'photologue:pl-photo-archive' %}">Photo date views
            <i class="fa fa-angle-double-right fa-lg" aria-hidden="true"></i>
        </a>


    </li>

</ul>

src/templates/_partial/slider.html
  {% load static %}
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" >
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'img/slider/slider-1.jpeg' %}" alt="First slide">
      <div class="carousel-caption d-none d-md-block"  style="background-color: green;">
        <h3>Heading goes here</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam quidem eius ut culpa eaque libero sed facilis, animi temporibus. Adipisci ratione ullam nisi officia ipsam saepe aut, amet unde alias.</p>
        <a href="#"><button class="btn btn-outline-info">View More</button></a>
 
      </div>
    </div>
    <div class="carousel-item">
      <img  class="d-block w-100" src="{% static 'img/slider/slider-2.jpeg' %}" alt="Second slide">
      <div class="carousel-caption d-none d-md-block" style="background-color: green;">
        <h3>Heading goes here</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam quidem eius ut culpa eaque libero sed facilis, animi temporibus. Adipisci ratione ullam nisi officia ipsam saepe aut, amet unde alias.</p>
        <a href="#"><button class="btn btn-outline-info">View More</button></a>

      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'img/slider/slider-3.jpeg' %}" alt="Third slide">
      <div class="carousel-caption d-none d-md-block"  style="background-color: green;">
        <h3>Heading goes here</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam quidem eius ut culpa eaque libero sed facilis, animi temporibus. Adipisci ratione ullam nisi officia ipsam saepe aut, amet unde alias.</p>
        <a href="#"><button class="btn btn-outline-info">View More</button></a>

      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

src/templates/_partial/statistics.html
    <div class="count    paralax mt-1" data-wow-delay="100ms" style="background-color: green;">
      <div class="container">
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <div class="text-center">
              <div class="icon"><i class="fa fa-group"></i></div>
              <div class="counter">
              <span class="timer">8298</span>
              </div>
              <div class="seperator-small"></div>
            <p>Students</p>
            </div>
          </div><!-- col-sm-3 -->
          <div class="col-xs-6 col-sm-3">
            <div class="text-center">
              <div class="icon"><i class="fa fa-book"></i></div>
              <div class="counter">
              <span class="timer">142</span>
              </div>
              <div class="seperator-small"></div>
              <p>Courses</p>
            </div>
          </div><!-- col-sm-3 -->
          <div class="col-xs-6 col-sm-3">
            <div class="text-center">
              <div class="icon"><i class="fa fa-male"></i></div>
              <div class="counter">
              <span class="timer">1047</span>
              </div>
              <div class="seperator-small"></div>
              <p>Stuffs</p>
            </div>
          </div><!-- col-sm-3 -->
          <div class="col-xs-6 col-sm-3">
            <div class="text-center">
              <div class="icon"><i class="fa fa-map-marker"></i></div>
              <div class="counter">
              <span class="timer">10</span>
              </div>
              <div class="seperator-small"></div>
              <p>Locations</p>
            </div>
          </div><!-- col-sm-3 -->
        </div><!-- row -->
        
      </div><!-- container -->
    </div><!-- count -->
    
  